BikeStoreMVC/Controllers/productController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BikeStoreMVC.Models;
using PagedList;

namespace BikeStoreMVC.Controllers
{
    public class productController : Controller
    {
        private BikeStoreEntities db = new BikeStoreEntities();

        // GET: product
        /*
        public ActionResult Index()
        {
            var tbl_product = db.tbl_product.Include(t => t.tbl_category).Include(t => t.tbl_colour).Include(t => t.tbl_description).Include(t => t.tbl_model).Include(t => t.tbl_size).Include(t => t.tbl_sub_category);
            return View(tbl_product.ToList());
        }
        */

            

        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.ModelSortParam = string.IsNullOrEmpty(sortOrder) ? "model_desc" : "";
            ViewBag.CategorySortParam = string.IsNullOrEmpty(sortOrder) ? "category_desc" : "";
            ViewBag.SubCategorySortParam = string.IsNullOrEmpty(sortOrder) ? "subcategory_desc" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            

            ViewBag.CurrentFilter = searchString;
            var tbl_product = db.tbl_product.Include(t => t.tbl_category).Include(t => t.tbl_colour).Include(t => t.tbl_model).Include(t => t.tbl_size).Include(t => t.tbl_sub_category);

            if (!String.IsNullOrEmpty(searchString))
            {
                tbl_product = tbl_product.Where(s => s.productName.Contains(searchString) || s.productCode.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "model_desc":
                    tbl_product = tbl_product.OrderByDescending(s => s.tbl_model.model);
                    break;
                case "category_desc":
                    tbl_product = tbl_product.OrderByDescending(s => s.tbl_category.category);
                    break;
                case "subcategory_desc":
                    tbl_product = tbl_product.OrderByDescending(s => s.tbl_sub_category.subcategory);
                    break;
                default:
                    tbl_product = tbl_product.OrderBy(s => s.tbl_model.model);
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);

            //return View(tbl_product.ToList());
            return View(tbl_product.ToPagedList(pageNumber, pageSize));
        }

        // GET: product/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_product tbl_product = db.tbl_product.Find(id);
            if (tbl_product == null)
            {
                return HttpNotFound();
            }
            return View(tbl_product);
        }

        // GET: product/Create
        public ActionResult Create()
        {
            var category = db.tbl_category.ToList();
            List<SelectListItem> li = new List<SelectListItem>();
            li.Add(new SelectListItem { Text = "[Select a category]", Value = "0" });
            foreach (var c in category)
            {
                li.Add(new SelectListItem { Text = c.category, Value = c.catID.ToString() });
                ViewBag.category = li;
            }

            //ViewBag.categoryID = new SelectList(db.tbl_category, "catID", "category");
            //ViewBag.subCategoryID = new SelectList(db.tbl_sub_category, "subID", "subCategory");
            ViewBag.colourID = new SelectList(db.tbl_colour, "colID", "colour");
            //ViewBag.modelID = new SelectList(db.tbl_model, "modID", "model");
            ViewBag.sizeID = new SelectList(db.tbl_size, "sizID", "size");
           
            return View();
        }

        public JsonResult getSubCategory(int id)
        {
            var subcats = db.tbl_sub_category.Where(x => x.catID == id).ToList();
            List<SelectListItem> lstSubCats = new List<SelectListItem>();
            lstSubCats.Add(new SelectListItem { Text = "[Select Sub Category]", Value = "0" });
            if (subcats != null)
            {
                foreach (var c in subcats)
                {
                    lstSubCats.Add(new SelectListItem { Text = c.subcategory, Value = c.subID.ToString() });
                }
            }
            return Json(new SelectList(lstSubCats, "Value", "Text", JsonRequestBehavior.AllowGet));
        }

        public JsonResult getModel(int id)
        {
            var models = db.tbl_model.Where(x => x.subID == id).ToList();
            List<SelectListItem> lstModels = new List<SelectListItem>();
            lstModels.Add(new SelectListItem { Text = "[Select Model]", Value = "0" });
            if (models != null)
            {
                foreach (var c in models)
                {
                    lstModels.Add(new SelectListItem { Text = c.model, Value = c.modID.ToString() });
                }
            }
            return Json(new SelectList(lstModels, "Value", "Text", JsonRequestBehavior.AllowGet));
        }

        // POST: product/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "proID,productCode,productName,categoryID,subCategoryID,modelID,price,colourID,sizeID,description")] tbl_product tbl_product)
        {
            if (ModelState.IsValid)
            {
                db.tbl_product.Add(tbl_product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.categoryID = new SelectList(db.tbl_category, "catID", "category", tbl_product.categoryID);
            ViewBag.colourID = new SelectList(db.tbl_colour, "colID", "colour", tbl_product.colourID);
            ViewBag.modelID = new SelectList(db.tbl_model, "modID", "model", tbl_product.modelID);
            ViewBag.sizeID = new SelectList(db.tbl_size, "sizID", "size", tbl_product.sizeID);
            ViewBag.subCategoryID = new SelectList(db.tbl_sub_category, "subID", "subcategory", tbl_product.subCategoryID);
            return View(tbl_product);
        }

        // GET: product/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_product tbl_product = db.tbl_product.Find(id);
            if (tbl_product == null)
            {
                return HttpNotFound();
            }
            var category = db.tbl_category.ToList();
            List<SelectListItem> li = new List<SelectListItem>();
            li.Add(new SelectListItem { Text = "[Select a category]", Value = "0" });
            foreach (var c in category)
            {
                li.Add(new SelectListItem { Text = c.category, Value = c.catID.ToString() });
                ViewBag.category = li;
            }
            //ViewBag.categoryID = new SelectList(db.tbl_category, "catID", "category", tbl_product.categoryID);
            ViewBag.colourID = new SelectList(db.tbl_colour, "colID", "colour", tbl_product.colourID);
            //ViewBag.modelID = new SelectList(db.tbl_model, "modID", "model", tbl_product.modelID);
            ViewBag.sizeID = new SelectList(db.tbl_size, "sizID", "size", tbl_product.sizeID);
            //ViewBag.subCategoryID = new SelectList(db.tbl_sub_category, "subID", "subcategory", tbl_product.subCategoryID);
            return View(tbl_product);
        }

        // POST: product/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "proID,productCode,productName,categoryID,subCategoryID,modelID,price,colourID,sizeID,description")] tbl_product tbl_product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbl_product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.categoryID = new SelectList(db.tbl_category, "catID", "category", tbl_product.categoryID);
            ViewBag.colourID = new SelectList(db.tbl_colour, "colID", "colour", tbl_product.colourID);
            ViewBag.modelID = new SelectList(db.tbl_model, "modID", "model", tbl_product.modelID);
            ViewBag.sizeID = new SelectList(db.tbl_size, "sizID", "size", tbl_product.sizeID);
            ViewBag.subCategoryID = new SelectList(db.tbl_sub_category, "subID", "subcategory", tbl_product.subCategoryID);
            return View(tbl_product);
        }

        // GET: product/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_product tbl_product = db.tbl_product.Find(id);
            if (tbl_product == null)
            {
                return HttpNotFound();
            }
            return View(tbl_product);
        }

        // POST: product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tbl_product tbl_product = db.tbl_product.Find(id);

BikeStoreMVC/Views/product/Create.cshtml
@model BikeStoreMVC.Models.tbl_product

@{
    ViewBag.Title = "Add Product";
}

<h2>Add A New Product</h2>
<script src="~/Scripts/jquery-3.1.1.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#categoryID").change(function () {
            $("#subCategoryID").empty();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("getSubCategory")',
                datatype: 'json',
                data: { id: $("#categoryID").val() },
                success: function (subcategories) {
                    $.each(subcategories, function (i, subcategory) {
                        $("#subCategoryID").append('<option value="' + subcategory.Value + '">' + subcategory.Text + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed to get sub categories' + ex);
                }
            });
            return false;
        })
    });
</script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#subCategoryID").change(function () {
            $("#modelID").empty();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("getModel")',
                datatype: 'json',
                data: { id: $("#subCategoryID").val() },
                success: function (models) {
                    $.each(models, function (i, model) {
                        $("#modelID").append('<option value="' + model.Value + '">' + model.Text + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed to get models' + ex);
                }
            });
            return false;
        })
    });
</script>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.productCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.productCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.productCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.productName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.productName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.productName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.categoryID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.DropDownList("categoryID", null, htmlAttributes: new { @class = "form-control" }) *@    
                @Html.DropDownList("categoryID", ViewBag.category as List<SelectListItem>, new { style = "width: 200px;" })
                @Html.ValidationMessageFor(model => model.categoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.subCategoryID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               @*@Html.DropDownList("subCategoryID", null, htmlAttributes: new { @class = "form-control" })*@
                @Html.DropDownList("subCategoryID", new SelectList(string.Empty, "Value", "Text"), "[Select Sub Category]", new { style = "width: 200px" }) 
                @Html.ValidationMessageFor(model => model.subCategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.modelID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.DropDownList("modelID", null, htmlAttributes: new { @class = "form-control" }) *@
                @Html.DropDownList("modelID", new SelectList(string.Empty, "Value", "Text"), "[Select Model]", new { style = "width: 200px" })
                @Html.ValidationMessageFor(model => model.modelID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.colourID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("colourID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.colourID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sizeID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("sizeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.sizeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" }})
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BikeStoreMVC/Views/product/Delete.cshtml
@model BikeStoreMVC.Models.tbl_product

@{
    ViewBag.Title = "Delete Product";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tbl_product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.productCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.productCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.productName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.productName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tbl_category.category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_category.category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tbl_colour.colour)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_colour.colour)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tbl_model.model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_model.model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tbl_size.size)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_size.size)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tbl_sub_category.subcategory)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_sub_category.subcategory)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BikeStoreMVC/Views/product/Details.cshtml
@model BikeStoreMVC.Models.tbl_product

@{
    ViewBag.Title = "Product Details";
}

<h2>Details</h2>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.productCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.productCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.productName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.productName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tbl_category.category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_category.category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tbl_colour.colour)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_colour.colour)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tbl_model.model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_model.model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tbl_size.size)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_size.size)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tbl_sub_category.subcategory)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_sub_category.subcategory)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.proID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BikeStoreMVC/Views/product/Edit.cshtml
@model BikeStoreMVC.Models.tbl_product

@{
    ViewBag.Title = "Edit Product";
}

<h2>Edit Product</h2>
<script src="~/Scripts/jquery-3.1.1.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#categoryID").change(function () {
            $("#subCategoryID").empty();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("getSubCategory")',
                datatype: 'json',
                data: { id: $("#categoryID").val() },
                success: function (subcategories) {
                    $.each(subcategories, function (i, subcategory) {
                        $("#subCategoryID").append('<option value="' + subcategory.Value + '">' + subcategory.Text + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed to get sub categories' + ex);
                }
            });
            return false;
        })
    });
</script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#subCategoryID").change(function () {
            $("#modelID").empty();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("getModel")',
                datatype: 'json',
                data: { id: $("#subCategoryID").val() },
                success: function (models) {
                    $.each(models, function (i, model) {
                        $("#modelID").append('<option value="' + model.Value + '">' + model.Text + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed to get models' + ex);
                }
            });
            return false;
        })
    });
</script>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Edit Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.proID)

        <div class="form-group">
            @Html.LabelFor(model => model.productCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.productCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.productCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.productName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.productName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.productName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.categoryID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("categoryID", ViewBag.category as List<SelectListItem>, new { style = "width: 200px;" })
                @Html.ValidationMessageFor(model => model.categoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.subCategoryID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("subCategoryID", new SelectList(string.Empty, "Value", "Text"), "[Select Sub Category]", new { style = "width: 200px" })
                @Html.ValidationMessageFor(model => model.subCategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.modelID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("modelID", new SelectList(string.Empty, "Value", "Text"), "[Select Model]", new { style = "width: 200px" })
                @Html.ValidationMessageFor(model => model.modelID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.colourID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("colourID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.colourID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sizeID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("sizeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.sizeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BikeStoreMVC/Views/product/Index.cshtml
@*@model IEnumerable<BikeStoreMVC.Models.tbl_product> *@
@model PagedList.IPagedList<BikeStoreMVC.Models.tbl_product>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Products";
}

<h2>Show Products</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("Index", "product", FormMethod.Get))
{
    <p>
        Find by product name or code: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}
<table class="table">
    <tr>
        <th>
            Product Code
        </th>
        <th>
           Product Name
        </th>
        <th>
           Price
        </th>
        <th>
            @Html.ActionLink("Category", "Index", new { sortOrder = ViewBag.CategorySortParam, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
           @Html.ActionLink("Sub Category", "Index", new { sortOrder = ViewBag.SubCategorySortParam, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Model", "Index", new { sortOrder = ViewBag.ModelSortParam, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            Colour
        </th>
        <th>
            Description
        </th>
        <th>
           Size
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.productCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.productName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tbl_category.category)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tbl_sub_category.subcategory)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tbl_model.model)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tbl_colour.colour)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>
        
        <td>
            @Html.DisplayFor(modelItem => item.tbl_size.size)
        </td>
        
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.proID }) |
            @Html.ActionLink("Details", "Details", new { id=item.proID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.proID })
        </td>
    </tr>
}

</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))